spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_social_network
    username: codekeys
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: codekeys.dev@gmail.com
    password: "aazl ekgz rtpx hnbq"
    properties:
      # On force l'écriture à plat ici pour éviter les erreurs d'interprétation
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true
      "[mail.smtp.ssl.enable]": false
        #connectiontimout: 5000
        #timeout: 3000
        #writetimeout: 5000
      protocol: smtp
application:
  security:
    jwt:
      secret-key: 7ce45867385f4e29acf35bf1a74f6f9b00a4d57c0b623738988e9e8f26759c6db15ec9ef6e25b2e01fe96e4b7c1f35c94c16fae0035c39d8a5fcbcf2c0fd4f4d
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8080

#aazl ekgz rtpx hnbq