name: BSN Backend API Pipeline

on:
  push:
    branches:
      - ci/pipeline
      - main
    paths:
      - bsn-network-backend/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml
env:
  EMAIL_HOST_NAME: localhost
  EMAIL_USERNAME: mama@gmail.com
  EMAIL_PASSWORD: test-password

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Compile project
        run: |
          cd bsn-network-backend
          chmod +x mvnw
          ./mvnw clean compile

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: book_social_network
          POSTGRES_USER: codekeys
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Running unit Tests
        run: |
          cd bsn-network-backend
          chmod +x mvnw
          ./mvnw clean test


  build:
    runs-on: ubuntu-latest
    name: Build backend
    needs:
      - compile
      - unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build project
        run: |
          cd bsn-network-backend
          chmod +x mvnw
          ./mvnw clean package


  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build project
        run: |
          cd bsn-network-backend
          chmod +x mvnw
          ./mvnw clean package

      - name: Extract project version
        id: extract_version
        run: |
          cd bsn-network-backend
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT  

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: bsn-network-backend
          file: docker/backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bsn-api:${{ steps.extract_version.outputs.VERSION}},${{ secrets.DOCKERHUB_USERNAME }}/bsn-api:latest
          build-args: |
            PROFILE=dev
            APP_VERSION=${{ steps.extract_version.outputs.VERSION}}
          

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Create deployment folder
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ci-cd"

      - name: Copy docker-compose file
        run: scp docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml

      - name: Set ENV variable and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          export EMAIL_HOST_NAME=${{ secrets.EMAIL_HOST_NAME }}
          export EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
          export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          cd ci-cd
          docker-compose -f docker-compose.yml pull -q 
          docker-compose -f docker-compose.yml up -d 
          EOF
          
